<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QMSFlowDoc.Domain\QMSFlowDoc.Domain.csproj" />
    <ProjectReference Include="..\QMSFlowDoc.Shared\QMSFlowDoc.Shared.csproj" />
    <ProjectReference Include="..\QMSFlowDoc.Application\QMSFlowDoc.Application.csproj" />
    <ProjectReference Include="..\QMSFlowDoc.Infrastructure\QMSFlowDoc.Infrastructure.csproj" />
    <ProjectReference Include="..\QMSFlowDoc.Web\QMSFlowDoc.Web.csproj" />
  </ItemGroup>

</Project>
